name: Server workflow

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/server.yml"
      - "package.json"
      - "server/**"

jobs:
  deploy-server:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Pull changes
        run: | 
          cd ~/cookin-up/
          git checkout master
          git reset --hard
          git pull origin master

      - name: Build
        run: |
          cd ~/cookin-up/server
          rm -rf ./publish
          dotnet publish -c Release -o ./publish
      - name: Deploy
        run: |
          sudo cp -r ~/cookin-up/server/publish/* /var/www/cookin-up-server/
          sudo systemctl restart cookin-up-server.service
